# Generated by Django 5.1.1 on 2024-09-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'initiated'), (3, 'Success'), (4, 'Failure')], default=1),
        ),
    ]
