# Generated by Django 5.1.1 on 2024-09-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='khalti_txn_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pidx',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Initiated'), (3, 'Success'), (4, 'Failure')], default=1),
        ),
    ]
